### ISSUE TITLE
萌新求教，这个怎么安装

### ISSUE THREAD

**Issue by 1357310795** [lyc8503/VizpowerHook#7]
😢

**Comment by lyc8503** [comment]
你首先需要安装一个Xposed框架, 最简单不会导致手机出问题的框架就是Virtual Xposed框架, 到这里https://vxposed.com/   下载.
下载过后导入无限宝和我发的插件(现在在鹅群1055109700里, 将来我会发到github).
然后在这个Virtual Xposed的框架里激活我的插件并重启就可以使用了.

**Comment by lyc8503** [comment]
至于 VirtualXposed 具体怎么操作在它的网站上也有, 你可以自己看一下.

**Comment by zhuguozheng** [comment]
手机安装xposed

**Comment by 1357310795** [comment]
谢谢提醒！

**Comment by lyc8503** [comment]
> 谢谢提醒！

你可以先试一下, 如果会了的话可以记得把issue close掉哦.

**Comment by 1357310795** [comment]
> > 谢谢提醒！
> 
> 你可以先试一下, 如果会了的话可以记得把issue close掉哦.

嗯

**Comment by Anguei** [comment]
@1357310795 现在 [Releases](https://github.com/lyc8503/VizpowerHook/releases) 里面有 apk 了
